using System.Text;

namespace DotNetMapper.Generator;

internal static class SourceEmitter
{
    public static string Emit(IReadOnlyCollection<MapCallModel> models)
    {
        if (models.Count == 0)
        {
            return string.Empty;
        }

        var grouped = models
            .GroupBy(static m => (m.InputType, m.OutputType))
            .OrderBy(static g => g.Key.InputType, StringComparer.Ordinal)
            .ThenBy(static g => g.Key.OutputType, StringComparer.Ordinal);

        var sb = new StringBuilder();
        sb.Append("// <auto-generated/>\n");
        sb.Append("#nullable disable\n");
        sb.Append('\n');
        sb.Append("namespace DotNetMapper.Generated\n");
        sb.Append("{\n");
        sb.Append("    file static class MapperInterceptors\n");
        sb.Append("    {\n");

        int methodIndex = 0;
        foreach (IGrouping<(string InputType, string OutputType), MapCallModel> group in grouped)
        {
            List<MapCallModel> ordered = group.OrderBy(static m => m.SortKey, StringComparer.Ordinal).ToList();

            foreach (MapCallModel model in ordered)
            {
                // LocationData is already valid inside a double-quoted string literal, so it is
                // emitted verbatim (Roslyn documents that no escaping is required).
                sb.Append($"        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute({model.LocationVersion}, \"{model.LocationData}\")]\n");
            }

            sb.Append($"        internal static {group.Key.OutputType} Map{methodIndex}({group.Key.InputType} inputObject)\n");
            sb.Append("        {\n");

            if (ordered[0].InputIsReferenceOrNullable)
            {
                sb.Append("            if (inputObject is null)\n");
                sb.Append("            {\n");
                sb.Append("                throw new global::System.ArgumentNullException(nameof(inputObject));\n");
                sb.Append("            }\n");
                sb.Append('\n');
            }

            sb.Append($"            return new {group.Key.OutputType}\n");
            sb.Append("            {\n");

            EquatableArray<string> properties = ordered[0].Properties;
            for (int i = 0; i < properties.Length; i++)
            {
                string comma = i == properties.Length - 1 ? string.Empty : ",";
                sb.Append($"                @{properties[i]} = inputObject.@{properties[i]}{comma}\n");
            }

            sb.Append("            };\n");
            sb.Append("        }\n");
            methodIndex++;
        }

        sb.Append("    }\n");
        sb.Append("}\n");
        sb.Append('\n');
        sb.Append("namespace System.Runtime.CompilerServices\n");
        sb.Append("{\n");
        sb.Append("    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]\n");
        sb.Append("    file sealed class InterceptsLocationAttribute : global::System.Attribute\n");
        sb.Append("    {\n");
        sb.Append("        public InterceptsLocationAttribute(int version, string data)\n");
        sb.Append("        {\n");
        sb.Append("            _ = version;\n");
        sb.Append("            _ = data;\n");
        sb.Append("        }\n");
        sb.Append("    }\n");
        sb.Append("}\n");

        return sb.ToString();
    }

}
